version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: orb-postgres
    environment:
      - POSTGRES_USER=orb
      - POSTGRES_PASSWORD=orb
      - POSTGRES_DB=orb
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5432"
    volumes:
      - ./prod/backend/data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: orb-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped
